project:
  type: website
  output-dir: docs

website:
  title: "Adri√°n **Zancajo**"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: CV.pdf
        text: CV  
      - text: Research
        menu: 
          - text: "Journal articles"
            href: Research.qmd#journal-articles
          - text: "Books"
            href: Research.qmd#books-page
          - text: "Book chapters"
            href: Research.qmd#book-chapters
          - text: "Reports and working papers"
            href: Research.qmd#reports-page
      - outreach.qmd

  page-footer:
    background: light # or `dark`

format:
  html:
    theme: 
      light: cosmo
    css: styles.css
    toc: true
    page-layout: article

editor: visual
